# requires azurefile storage class to be defined on global level
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vehicle-maintenance-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
