apiVersion: v1
kind: Service
metadata:
  name: vehicle-maintenance-service
  labels:
    do-not-recreate: "true"
spec:
  selector:
    app: vehicle-maintenance
  ports:
    - name: vehicle-maintenance1
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
